### ISSUE TITLE
`docker.yml` Dockerhub Integration

### ISSUE THREAD

**Issue by Sweetdevil144** [PecanProject/pecan#3404]
## Description

**Is your feature request related to a problem? Please describe.**
Current Workflow gives me an error `Error: Username and password required` while trying to `Login into DockerHub`.

## Proposed Solution
Maybe we can enhance this by providing user an option to use their `DOCKER_USERNAME` or `DOCKER_PASSWORD` from secrets. Maybe further additions as below :
```yml
jobs:
  docker_login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
```
